version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install poetry
            poetry install

      - run:
          name: Run tests
          command: |
            pip install pytest
            python -c "import sys; sys.path.append('/root/project')"
            python -m pytest

workflows:
  version: 2
  test:
    jobs:
      - build
