version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests/
      - store_artifacts:
          path: test-reports/*.py
          destination: python_app
